### PR TITLE
fix: remove unused env var

### PR DESCRIPTION
**Pull request by usirin**
remove unused env var, it fixes build errors.

### CODE REVIEW

**Comment by puskuruk** [comment]
We'll need that for our new backend URL

**Comment by usirin** [comment]
@puskuruk let's add that when we need it. i don't want to have a BASE_URL that doesn't exist for now.

Oh, actually we can just comment it out? the error case was blocking the builds.

**Comment by puskuruk** [comment]
Ok, we can update it when we have backend URL

**Comment by usirin** [comment]
I've commented them out instead of deleting them. and updated `.env.sample` to include an empty env variable to let us remember what we need to fill out.

I'll merge it when you approve. Then rebase your PR to include my change so we can get it building as well.

**Review by puskuruk — APPROVED** [review]

**Comment by usirin** [comment]
I've just realized i actually didn't commit the "commenting out" change. they are removed. my bad 🤦

**Pull request merged**
